## Lab 1 - Foundations of Deep Learning

In [2]:
import math
import numpy as np

In [12]:
def basic_sigmoid(x):
    """
    Compute sigmoid of x.
    
    Arguments:
    x -- A scalar
    
    return:
    s -- sigmoid(x)
    """
    s=1/(1+math.exp(-x))
    return s

In [13]:
basic_sigmoid(-1)

0.2689414213699951

In [14]:
x=np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [15]:
x=np.array([1,2,3])
print(x+3)

[4 5 6]


In [16]:
import numpy as np
def sigmoid(x):
    """
    Compute sigmoid of x.
    
    Arguments:
    x -- A scalar or numpy array of any size
    
    return:
    s -- sigmoid(x)
    """
    
    s=1/(1+np.exp(-x))
    return s

In [17]:
x=np.array([1,2,3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [18]:
def image2vector(image):
    return image.reshape(-1, 1)

In [19]:
image = np.array([
    [[0, 0, 0], [255, 0, 0], [0, 255, 0]],
    [[0, 0, 255], [255, 255, 0], [0, 255, 255]],
    [[255, 0, 255], [192, 192, 192], [128, 128, 128]]
])

image_vector = image2vector(image)
image_vector

array([[  0],
       [  0],
       [  0],
       [255],
       [  0],
       [  0],
       [  0],
       [255],
       [  0],
       [  0],
       [  0],
       [255],
       [255],
       [255],
       [  0],
       [  0],
       [255],
       [255],
       [255],
       [  0],
       [255],
       [192],
       [192],
       [192],
       [128],
       [128],
       [128]])

In [20]:
def normalizeRows(x):
    row_norms = np.linalg.norm(x, axis=1, keepdims=True)
    normalized_x = x / row_norms
    return normalized_x

x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

normalized_x = normalizeRows(x)
normalized_x 

array([[0.26726124, 0.53452248, 0.80178373],
       [0.45584231, 0.56980288, 0.68376346],
       [0.50257071, 0.57436653, 0.64616234]])

In [25]:
def softmax(x):
    x_exp = np.exp(x)
    sum_x_exp = np.sum(x_exp, axis=1, keepdims=True)
    softmax_x = x_exp / sum_x_exp
    return softmax_x

x = np.array([[1, 2, 3],
              [1, 2, 3],
              [1, 2, 3]])

softmax_x = softmax(x)
softmax_x

array([[0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096]])

In [29]:
import time
import numpy as np

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]

x1 = np.random.rand(100000).tolist()
x2 = np.random.rand(100000).tolist()

dot_product = 0
start_time = time.time()
for i in range(len(x1)):
    dot_product += x1[i] * x2[i]
end_time = time.time()

elapsed_time_for_loop = end_time - start_time

print("Dot product:", dot_product)
print("Time taken:", elapsed_time_for_loop, "seconds")


x1_np = np.array(x1)
x2_np = np.array(x2)

start_time = time.time()
dot_product_np = np.dot(x1_np, x2_np)
end_time = time.time()

elapsed_time_numpy = end_time - start_time

print("Dot product using NumPy:", dot_product_np)
print("Time taken using NumPy:", elapsed_time_numpy, "seconds")

time_difference = elapsed_time_for_loop - elapsed_time_numpy
print("Time difference:", time_difference, "seconds")

Dot product: 25067.749129159656
Time taken: 0.0750722885131836 seconds
Dot product using NumPy: 25067.749129159638
Time taken using NumPy: 0.0780494213104248 seconds
Time difference: -0.002977132797241211 seconds


In [3]:
def l1_loss(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

y_true = np.array([1.0, 2.0, 3.0])
y_pred = np.array([1.2, 1.9, 3.1])

l1 = l1_loss(y_true, y_pred)
l1

0.1333333333333334

In [4]:
def l2_loss(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

y_true = np.array([1.0, 2.0, 3.0])
y_pred = np.array([1.2, 1.9, 3.1])

l2 = l2_loss(y_true, y_pred)
l2

0.020000000000000004